apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: secrets-ns
spec:
  provider: aws
  parameters:
    region: eu-west-2
    objects: |
      - objectName: staging/myapp-secret-vs
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: username
          key: k8s-myusername
        - objectName: password
          key: k8s-mypassword
